### ISSUE TITLE
CSS Not Applying To New Page

### ISSUE THREAD

**Issue by julianredmond** [julianredmond/julianredmond.ca#11]
I'm trying to add a page to my portfolio website and the content is showing up unstyled. Do you know why that might be?

Thanks

@thomasjbradley

**Comment by thomasjbradley** [comment]
You need a `/` at the start of the `href` on this line:
https://github.com/julianredmond/julianredmond.ca/blob/master/_layouts/default.html#L7

`href="/css/main.css"`

**Comment by julianredmond** [comment]
Thanks Thomas!
